"""
MindfulAI Chat Routes - Simplified
The AI call is handled directly from the frontend using the Anthropic API.
This backend only handles: message storage, history, emotion detection, crisis detection.
"""

from flask import Blueprint, request, jsonify, current_app
from database.db import query_all, execute
from modules.auth import login_required
from modules.chatbot import detect_emotion, detect_crisis, get_activity, get_crisis_response

chat_bp = Blueprint("chat", __name__)


@chat_bp.route("/message", methods=["POST"])
@login_required
def send_message(current_user):
    """
    Store user message and return emotion/crisis data.
    The actual AI reply is generated by the frontend and then saved via /save_reply.
    """
    data    = request.get_json() or {}
    content = (data.get("message") or "").strip()
    mood    = data.get("mood")

    if not content:
        return jsonify({"error": "Message cannot be empty"}), 400

    user_id = current_user["id"]

    # Detect emotion and crisis locally (no API call needed)
    emotion   = detect_emotion(content)
    is_crisis = detect_crisis(content)

    # Save user message to DB
    execute(
        "INSERT INTO chat_messages (user_id, role, content, emotion, is_crisis) VALUES (?,?,?,?,?)",
        (user_id, "user", content, emotion, int(is_crisis))
    )

    # Load recent history for context (sent to frontend for AI call)
    history = query_all(
        "SELECT role, content FROM chat_messages WHERE user_id=? ORDER BY created_at DESC LIMIT 20",
        (user_id,)
    )
    history = list(reversed(history))

    payload = {
        "emotion":   emotion,
        "is_crisis": is_crisis,
        "history":   history,
        "user_name": current_user["name"],
        "mood":      mood,
    }

    if emotion in ("sad", "anxious", "stressed", "angry"):
        payload["activity"] = get_activity(emotion)

    if is_crisis:
        payload["helplines"]       = current_app.config.get("HELPLINES", {})
        payload["crisis_response"] = get_crisis_response()

    return jsonify(payload)


@chat_bp.route("/save_reply", methods=["POST"])
@login_required
def save_reply(current_user):
    """Save the AI reply generated by the frontend into the database."""
    data    = request.get_json() or {}
    content = (data.get("reply") or "").strip()
    emotion = data.get("emotion", "neutral")

    if not content:
        return jsonify({"error": "Reply cannot be empty"}), 400

    execute(
        "INSERT INTO chat_messages (user_id, role, content, emotion, is_crisis) VALUES (?,?,?,?,?)",
        (current_user["id"], "assistant", content, emotion, 0)
    )
    return jsonify({"saved": True})


@chat_bp.route("/history", methods=["GET"])
@login_required
def get_history(current_user):
    limit = min(int(request.args.get("limit", 50)), 200)
    rows = query_all(
        """SELECT role, content, emotion, is_crisis, created_at
           FROM chat_messages WHERE user_id=?
           ORDER BY created_at DESC LIMIT ?""",
        (current_user["id"], limit)
    )
    return jsonify({"messages": list(reversed(rows))})


@chat_bp.route("/history", methods=["DELETE"])
@login_required
def clear_history(current_user):
    execute("DELETE FROM chat_messages WHERE user_id=?", (current_user["id"],))
    return jsonify({"message": "Chat history cleared"})


@chat_bp.route("/activity", methods=["GET"])
@login_required
def get_activity_suggestion(current_user):
    emotion = request.args.get("emotion", "neutral")
    return jsonify({"activity": get_activity(emotion), "emotion": emotion})
