"""
MindfulAI Journal Routes - Simplified
AI insights are generated by the frontend directly.
Backend only stores entries and detects emotion locally.
"""

from flask import Blueprint, request, jsonify
from database.db import query_all, query_one, execute
from modules.auth import login_required
from modules.chatbot import detect_emotion

journal_bp = Blueprint("journal", __name__)


@journal_bp.route("/", methods=["POST"])
@login_required
def create_entry(current_user):
    data    = request.get_json() or {}
    content = (data.get("content") or "").strip()
    mood    = data.get("mood")
    insight = data.get("ai_insight")   # frontend sends AI insight directly

    if not content:
        return jsonify({"error": "Journal entry cannot be empty"}), 400

    emotion = detect_emotion(content)

    entry_id = execute(
        "INSERT INTO journal_entries (user_id, content, mood, emotion, ai_insight) VALUES (?,?,?,?,?)",
        (current_user["id"], content, mood, emotion, insight)
    )

    return jsonify({"id": entry_id, "emotion": emotion, "saved": True}), 201


@journal_bp.route("/", methods=["GET"])
@login_required
def list_entries(current_user):
    page     = max(1, int(request.args.get("page", 1)))
    per_page = min(int(request.args.get("per_page", 20)), 50)
    offset   = (page - 1) * per_page

    total = query_one(
        "SELECT COUNT(*) as n FROM journal_entries WHERE user_id=?",
        (current_user["id"],)
    )["n"]

    entries = query_all(
        """SELECT id, content, mood, emotion, ai_insight, created_at
           FROM journal_entries WHERE user_id=?
           ORDER BY created_at DESC LIMIT ? OFFSET ?""",
        (current_user["id"], per_page, offset)
    )

    return jsonify({
        "entries":  entries,
        "total":    total,
        "page":     page,
        "per_page": per_page,
        "has_more": (offset + per_page) < total,
    })


@journal_bp.route("/<int:entry_id>", methods=["GET"])
@login_required
def get_entry(current_user, entry_id):
    entry = query_one(
        "SELECT * FROM journal_entries WHERE id=? AND user_id=?",
        (entry_id, current_user["id"])
    )
    if not entry:
        return jsonify({"error": "Entry not found"}), 404
    return jsonify({"entry": entry})


@journal_bp.route("/<int:entry_id>", methods=["DELETE"])
@login_required
def delete_entry(current_user, entry_id):
    entry = query_one(
        "SELECT id FROM journal_entries WHERE id=? AND user_id=?",
        (entry_id, current_user["id"])
    )
    if not entry:
        return jsonify({"error": "Entry not found"}), 404
    execute("DELETE FROM journal_entries WHERE id=?", (entry_id,))
    return jsonify({"deleted": True})


@journal_bp.route("/<int:entry_id>/insight", methods=["POST"])
@login_required
def save_insight(current_user, entry_id):
    """Save an AI insight generated by the frontend."""
    data    = request.get_json() or {}
    insight = (data.get("insight") or "").strip()

    entry = query_one(
        "SELECT id FROM journal_entries WHERE id=? AND user_id=?",
        (entry_id, current_user["id"])
    )
    if not entry:
        return jsonify({"error": "Entry not found"}), 404

    execute("UPDATE journal_entries SET ai_insight=? WHERE id=?", (insight, entry_id))
    return jsonify({"saved": True, "insight": insight})
